# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/ECE544-EmbeddedSystemsFPGA/ece544w25_proj1/ECE544-Project1/ECE544-Project1.srcs/sources_1/bd/embsys/ip/embsys_lmb_bram_1/embsys_lmb_bram_1.xci
# IP: The module: 'embsys_lmb_bram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECE544-EmbeddedSystemsFPGA/ece544w25_proj1/ECE544-Project1/ECE544-Project1.gen/sources_1/bd/embsys/ip/embsys_lmb_bram_1/embsys_lmb_bram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_lmb_bram_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/ECE544-EmbeddedSystemsFPGA/ece544w25_proj1/ECE544-Project1/ECE544-Project1.srcs/sources_1/bd/embsys/ip/embsys_lmb_bram_1/embsys_lmb_bram_1.xci
# IP: The module: 'embsys_lmb_bram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECE544-EmbeddedSystemsFPGA/ece544w25_proj1/ECE544-Project1/ECE544-Project1.gen/sources_1/bd/embsys/ip/embsys_lmb_bram_1/embsys_lmb_bram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_lmb_bram_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
