# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/ECE544-EmbeddedSystemsFPGA/ece544w25_proj1/constraints/nexysA7fpga.xdc

# Block Designs: bd/embsys/embsys.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys || ORIG_REF_NAME==embsys} -quiet] -quiet

# IP: bd/embsys/ip/embsys_xbar_0/embsys_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_xbar_0 || ORIG_REF_NAME==embsys_xbar_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_axi_periph_0/embsys_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_axi_periph_0 || ORIG_REF_NAME==embsys_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_axi_intc_0/embsys_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_axi_intc_0 || ORIG_REF_NAME==embsys_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_xlconcat_0/embsys_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_xlconcat_0 || ORIG_REF_NAME==embsys_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_mdm_1_0/embsys_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_mdm_1_0 || ORIG_REF_NAME==embsys_mdm_1_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_clk_wiz_1_0/embsys_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_clk_wiz_1_0 || ORIG_REF_NAME==embsys_clk_wiz_1_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_rst_clk_wiz_1_100M_0/embsys_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==embsys_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_fit_timer_0_0/embsys_fit_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_fit_timer_0_0 || ORIG_REF_NAME==embsys_fit_timer_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_timer_0_0/embsys_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_timer_0_0 || ORIG_REF_NAME==embsys_axi_timer_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_gpio_0_0/embsys_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_0_0 || ORIG_REF_NAME==embsys_axi_gpio_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_nexys4io_0_0/embsys_nexys4io_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_nexys4io_0_0 || ORIG_REF_NAME==embsys_nexys4io_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_PWM_Analyzer_0_0/embsys_PWM_Analyzer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_PWM_Analyzer_0_0 || ORIG_REF_NAME==embsys_PWM_Analyzer_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_PWM_Analyzer_1_0/embsys_PWM_Analyzer_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_PWM_Analyzer_1_0 || ORIG_REF_NAME==embsys_PWM_Analyzer_1_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_PWM_Analyzer_2_0/embsys_PWM_Analyzer_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_PWM_Analyzer_2_0 || ORIG_REF_NAME==embsys_PWM_Analyzer_2_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_rgbPWM_0_0/embsys_rgbPWM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_rgbPWM_0_0 || ORIG_REF_NAME==embsys_rgbPWM_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_proc_sys_reset_0_0/embsys_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_proc_sys_reset_0_0 || ORIG_REF_NAME==embsys_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_1/embsys_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_1 || ORIG_REF_NAME==embsys_microblaze_0_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_dlmb_v10_1/embsys_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_dlmb_v10_1 || ORIG_REF_NAME==embsys_dlmb_v10_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_ilmb_v10_1/embsys_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_ilmb_v10_1 || ORIG_REF_NAME==embsys_ilmb_v10_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_dlmb_bram_if_cntlr_1/embsys_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==embsys_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_ilmb_bram_if_cntlr_1/embsys_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==embsys_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_lmb_bram_1/embsys_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_lmb_bram_1 || ORIG_REF_NAME==embsys_lmb_bram_1} -quiet] -quiet

# XDC: c:/ECE544-EmbeddedSystemsFPGA/ece544w25_proj1/ECE544-Project1/ECE544-Project1.gen/sources_1/bd/embsys/embsys_ooc.xdc
